package edu.salisbury.core_simulator;


/**
 * Class used to keep track a pair of {@link Coordinate Coordinates}, 
 * e.g. {(x1,y1), (x2,y2)}
 * @author timfoil
 */
public class CoordinatePair
{
	private Coordinate coord1;
	private Coordinate coord2;
	
	/**
	 * Constructor for a CoordinatePair. The two coordinates are initialized to (0,0).
	 */
	public CoordinatePair()
	{
		coord1 = new Coordinate(0,0);
		coord2 = new Coordinate(0,0);
	}
	
	/**
	 * Constructor for a coordinatePair, takes two {@link Coordinate} objects.
	 *
	 * @param coordinate1 first coordinate
	 * @param coordinate2 second coordinate
	 */
	public CoordinatePair(Coordinate coordinate1, Coordinate coordinate2)
	{
		coord1 = coordinate1;
		coord2 = coordinate2;
	}
	
	/**
	 * Constructor for a CoordinatePair, takes one {@link Coordinate} object
	 * for the first coordinate and two ints to construct the second 
	 * coordinate.
	 * @param coordinate1 first coordinate
	 * @param x2 x value for the second coordinate
	 * @param y2 y value for the second coordinate
	 */
	public CoordinatePair(Coordinate coordinate1, int x2, int y2)
	{
		coord1 = coordinate1;
		coord2 = new Coordinate(x2, y2);
	}
	
	/**
	 * Constructor for a CoordinatePair, takes two ints to construct the first 
	 * {@link Coordinate} and one coordinate object for the second coordinate.
	 * @param coordinate1 first coordinate
	 * @param x2 x value for the second coordinate
	 * @param y2 y value for the second coordinate
	 */
	public CoordinatePair(int x1, int y1, Coordinate coordinate2)
	{
		coord1 = new Coordinate(x1,y1);
		coord2 = coordinate2;
	}
	
	/**
	 * Getter for the first {@link Coordinate}.
	 * @return coord1
	 */
	public Coordinate coord1()
	{
		return coord1;
	}
	
	/**
	 * Getter for the second {@link Coordinate}.
	 * @return coord2
	 */
	public Coordinate coord2()
	{
		return coord2;
	}
	
	/**
	 * Setter for the first {@link Coordinate}.
	 * @return coord
	 */
	public void setCoord1(Coordinate coord)
	{
		coord1 = coord;
	}
	
	/**
	 * Setter for the second {@link Coordinate}.
	 * @param coord
	 */
	public void setCoord2(Coordinate coord)
	{
		coord2 = coord;
	}
	
	@Override
	public String toString()
	{
		return "{" + coord1 + ", " + coord2 + "}";
	}

	@Override
	//Generated by eclipse
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((coord1 == null) ? 0 : coord1.hashCode());
		result = prime * result + ((coord2 == null) ? 0 : coord2.hashCode());
		return result;
	}

	@Override
	//Generated by eclipse
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CoordinatePair other = (CoordinatePair) obj;
		if (coord1 == null)
		{
			if (other.coord1 != null)
				return false;
		} else if (!coord1.equals(other.coord1))
			return false;
		if (coord2 == null)
		{
			if (other.coord2 != null)
				return false;
		} else if (!coord2.equals(other.coord2))
			return false;
		return true;
	}
}
