package edu.salisbury.photonic.core_simulator;

/**
 * Coordinate class for the basic layout test scheme
 * 
 * <p>Increasing Y indicates cores in rightward direction.
 * Increasing X indicates cores in downward direction
 * <p>Due to this the origin of the coord system is at the top leftmost corner.
 * 
 * @author timfoil
**/
public class Coordinate 
{
	private int coordX;
	private int coordY;
	
	/**
	 * Constructor, takes an x and y coordinate
	 * 
	 * @param x
	 * @param y 
	 */
	public Coordinate(int x, int y)
	{
		this.coordX = x;
		this.coordY = y;
	}
	
	/**
	 * Constructor with no args defaults to a coordinate value of (0,0)
	 */
	public Coordinate()
	{
		this.coordX = 0;
		this.coordY = 0;
	}
	
	/**
	 * Constructor that constructs a copy of the given coordinate object.
	 * @param toCopy the Coordinate to copy
	 */
	public Coordinate(Coordinate toCopy)
	{
		this.coordX = toCopy.coordX;
		this.coordY = toCopy.coordY;
	}
	
	/**
	 * getter for X value
	 * @return X
	 */
	public int getX()
	{
		return coordX;
	}
	
	/**
	 * getter for Y value
	 * @return Y
	 */
	public int getY()
	{
		return coordY;
	}
	
	public String toString()
	{
		return "(" + this.coordX + ", " + this.coordY + ")";
	}


	@Override
	//generated by eclipse
	public int hashCode() 
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + coordX;
		result = prime * result + coordY;
		return result;
	}

	@Override
	//generated by eclipse
	public boolean equals(Object obj) 
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Coordinate other = (Coordinate) obj;
		if (coordX != other.coordX)
			return false;
		if (coordY != other.coordY)
			return false;
		return true;
	}
	
}
